### ISSUE TITLE
[Proposal] 광야에 스레드 기능 추가 

### ISSUE THREAD

**Issue by MagicalLas** [themoment-team/GSM-Networking-server#104]
광야에서 여러 이야기를 나누기는 하지만, 흘러가는 메시지들 속에서 긴 대화를 나누기 어렵습니다.
슬랙과 같은 스레드 기능을 도입하여 더 많은 이야기를 특정 주제에 대하여 이야기를 나눌 수 있으면 좋겠습니다.

간단하게 제안해봅니당ㅋㅋ

**Comment by YangSiJun528** [comment]
GSM Networking에 관심 가져주셔서 감사합니다! 😀

GSM Networking에서 광야를 만든 이유는 동문들의 니즈를 파악하기 위한 가벼운 서비스를 제공하는 것입니다.
한 주제에 대해서 깊게 이야기하기 위해 스레드 기능을 도입하는 의견은 감사하지만, 
광야의 제작 목적과 달라 스레드 기능 추가는 어려울 것 같습니다.

다만, 말씀해주신 불편함은 더모먼트 팀에서도 인지하고 있고,
현재 특정 토픽에 더 깊게 대화할 수 있는 게시판 형태의 커뮤니티를 구상 중에 있습니다.

만약 구상 중인 게시판 형태의 커뮤니티에 관심 있으시다면, 언제라도 말씀해주세요!
